<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.staitech</groupId>
        <artifactId>staitech-modules</artifactId>
        <version>2.6.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>staitech-modules-image</artifactId>

    <description>
        原始切片解析服务
    </description>

    <dependencies>
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>swagger-bootstrap-ui</artifactId>
            <version>1.9.6</version>
        </dependency>
        <!-- SpringCloud Alibaba Nacos -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <!-- SpringCloud Alibaba Nacos Config -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>

        <!-- SpringCloud Alibaba Sentinel -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
        </dependency>

        <!-- SpringBoot Actuator -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <!-- Swagger UI -->
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>${swagger.fox.version}</version>
        </dependency>

        <!-- Mysql Connector -->
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>

        <!-- Staitech Common DataSource -->
        <dependency>
            <groupId>cn.staitech</groupId>
            <artifactId>staitech-common-datasource</artifactId>
        </dependency>

        <!-- Staitech Common DataScope -->
        <dependency>
            <groupId>cn.staitech</groupId>
            <artifactId>staitech-common-datascope</artifactId>
        </dependency>

        <!-- Staitech Common Log -->
        <dependency>
            <groupId>cn.staitech</groupId>
            <artifactId>staitech-common-log</artifactId>
        </dependency>

        <!-- Staitech Common Swagger -->
        <dependency>
            <groupId>cn.staitech</groupId>
            <artifactId>staitech-common-swagger</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity-tools</artifactId>
            <version>2.0</version>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-websocket</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <!-- mybatis-plus -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.3.0</version>
        </dependency>

        <dependency>
            <groupId>com.github.yulichang</groupId>
            <artifactId>mybatis-plus-join-boot-starter</artifactId>
            <version>1.4.5</version>
        </dependency>

        <!--redisson-->
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson</artifactId>
            <version>3.8.2</version>
        </dependency>

        <!-- FastDFS -->
        <dependency>
            <groupId>com.github.tobato</groupId>
            <artifactId>fastdfs-client</artifactId>
        </dependency>

        <!-- Minio -->
        <dependency>
            <groupId>io.minio</groupId>
            <artifactId>minio</artifactId>
            <version>${minio.version}</version>
        </dependency>
        <!-- openslide -->
        <dependency>
            <groupId>org.openslide</groupId>
            <artifactId>openslide</artifactId>
            <version>3.4.1</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/resources/lib/openslide.jar</systemPath>
        </dependency>

        <!-- opencv -->
        <dependency>
            <groupId>org.opencv</groupId>
            <artifactId>opencv</artifactId>
            <version>4.2</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/resources/lib/opencv-420.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>5.12.1</version>
        </dependency>
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna-platform</artifactId>
            <version>5.12.1</version>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.7.16</version>
        </dependency>
    </dependencies>
    <repositories>
        <repository>
            <id>aliyun</id>
            <url>https://maven.aliyun.com/repository/public</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
    <build>
        <finalName>${project.artifactId}</finalName>

        <resources>
            <!--<resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>-->
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>**/*.*</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.xml</include>
                </includes><!-- maven可以将mapper.xml进行打包处理，否则仅对java文件处理 -->
            </resource>


            <!-- 放置通用配置yml文件， 开发时仅配置一套参数即可。   实际生产环境下应在每个项目下 与jar同级目录下新建application.yml覆写对应参数。  -->
            <resource>
                <directory>../conf/devCommons</directory>
                <includes>
                    <include>**/*.yml</include>
                </includes>
            </resource>

            <!-- 增加内容:MAVEN打包找不到本地LIB目录下的jar包解决办法 https://blog.csdn.net/asdfadafd/article/details/123985540  -->
            <resource>
                <!--需要打包的jar路径-->
                <directory>src/main/resources/lib</directory>
                <!--复制到的路径-->
                <targetPath>BOOT-INF/lib/</targetPath>
                <includes>
                    <include>**/*.jar</include>
                </includes>
            </resource>
        </resources>


        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <!--配置profiles环境-->
    <profiles>
        <profile>
            <!--开发环境-->
            <id>pacmvsdev</id>
            <properties>
                <activatedProperties>pacmvsdev</activatedProperties>
                <nacosNamespace>pacmvsdev</nacosNamespace>
                <nacosAddress>http://192.168.52.224:8848</nacosAddress>
                <nacosGroup>DEFAULT_GROUP</nacosGroup>
                <serverAddr>192.168.52.224:8848</serverAddr>
            </properties>
        </profile>
        <profile>
            <!--测试环境-->
            <id>testpvcmvs</id>
            <properties>
                <activatedProperties>testpvcmvs</activatedProperties>
                <nacosNamespace>301f5c59-5f9c-451c-a77b-88d64ddfd9f0</nacosNamespace>
                <nacosAddress>http://192.168.160.105:8848</nacosAddress>
                <nacosGroup>DEFAULT_GROUP</nacosGroup>
                <serverAddr>192.168.160.105:8848</serverAddr>
            </properties>
        </profile>
        <profile>
            <!--生产环境-->
            <id>pathmedics</id>
            <properties>
                <activatedProperties>pathmedics</activatedProperties>
                <nacosNamespace>40438ad6-00f6-4524-8043-4e79819cccf0</nacosNamespace>
                <nacosAddress>http://10.10.4.13:8848</nacosAddress>
                <nacosGroup>DEFAULT_GROUP</nacosGroup>
                <serverAddr>10.10.4.13:8848</serverAddr>
            </properties>
        </profile>

    </profiles>
</project>